### ISSUE TITLE
GPU features

### ISSUE THREAD

**Issue by wesleyliwei** [ZJUCVG/ENFT-SfM#1]
Dear,
Does this lib support any GPU option?
such as sift feature extraction, feature matching etc.

Thanks and Best Regards,
Wesley

**Comment by ZJUCVG** [comment]
Hi, Wesley
ENFT-SfM has already been using OpenGL to accelerate SIFT feature extraction and feature matching.
You can find GLSL source code in `ENFT/ProgramGL/`.
