### ISSUE TITLE
How to visualize the result

### ISSUE THREAD

**Issue by CanCanZeng** [ZJUCVG/ENFT-SfM#2]
Thank you for sharing this great project.
I build it from source on Ubuntu16.04, it rans well, but at last the result is save as result.act. I did not find any guide on how to visualize it, is there any way to transform it to PLY or OBJ format file?

**Comment by oneLOH** [comment]
you can add view=1 in configuration file to show the result.

**Comment by jsYangCode** [comment]
@CanCanZeng , Hi, friend! i have build it well from the instruction of 5.Usage without 4.Dependencies. But when i run it, something is wrong as : (terminate called after throwing an instance of 'CVD::Exceptions::Image_IO::OpenError'). i wondered whether the Dependencies should must be built from source? look forward to your reply, Thank you！

**Comment by HuangTY96** [comment]
> @CanCanZeng , Hi, friend! i have build it well from the instruction of 5.Usage without 4.Dependencies. But when i run it, something is wrong as : (terminate called after throwing an instance of 'CVD::Exceptions::Image_IO::OpenError'). i wondered whether the Dependencies should must be built from source? look forward to your reply, Thank you！

Hi, friend, I have the same problem just like yours, do you solve it?
Actually, no matter I use ubuntu16.04 or windows10 with visual studio2015, I have the same question.

**Comment by oneLOH** [comment]
Hi, you can recompile [CVD](https://github.com/edrosten/libcvd/releases/tag/RELEASE_20121025.2) with the option `--with-png` enabled.

**Comment by HuangTY96** [comment]
> Hi, you can recompile [CVD](https://github.com/edrosten/libcvd/releases/tag/RELEASE_20121025.2) with the option `--with-png` enabled.

thx!

**Comment by Sandeldeng** [comment]
I want to know is anybody know how to show the final result. look forward to your guys replay.

**Comment by TheRustlessSummer** [comment]
> I want to know is anybody know how to show the final result. look forward to your guys replay.

Hello, have you solved the program? I also meet with the question that I cant open result.act.
